### ISSUE TITLE
Segmentation failure 

### ISSUE THREAD

**Issue by JesusChapman** [suhan-paradkar/java-in-termux#3]
Hello, I have an armv7l device, and java 8 throws me a segmentation failure

**Comment by creepy-pasta101** [comment]
> Hello, I have an armv7l device, and java 8 throws me a segmentation failure

That seems to be an issue of Openjdk binaries provided by @Hax4us ...

**Comment by creepy-pasta101** [comment]
Refer Hax4us/java#20
